### ISSUE TITLE
Broken URLs

### ISSUE THREAD

**Issue by Mennaruuk** [10cella/awesome-quic#3]
- qlog 0.4.0 link is down. I'd recommend directly linking to the respective [docs.rs page](https://docs.rs/qlog/0.4.0/qlog/index.html).
- aioquic link is https://github.com/aiortc/aioquic
- Haskell quic link is https://github.com/kazu-yamamoto/quic
- Sadly, I couldn't find any archive of the now-gone article **_[The New Internet: HTTP/3 — No More TCP, let’s QUIC fix it](https://thexbhpguy.medium.com/the-new-internet-http-3-no-more-tcp-lets-quic-fix-it-6a4cbb6280c7)_**.

By the way, thank you for maintaining this list, it's helpful for a lot of people!!

**Comment by xiaojian-hong** [comment]
Hi @Mennaruuk ,

Thanks for your contribution, I just fixed the broken URLs.

About the article "The New Internet: HTTP/3 — No More TCP, let’s QUIC fix it.", unfortunately I can't find the archive either, seems the author's account was banned. I removed this article from `QUIC Weekly` for now.

**Comment by Mennaruuk** [comment]
Appreciate your assistance! Hope you have a good day/night :)
